title: Umbra Solis
description: Updates, worldbuilding, characters, and more
theme: minima

# Custom navigation links
header_pages:
  - index.md
  - Characterindex.md
  - Places/Places.md
  - Updates/Updates.md
  - about.md

