title: "Umbra Solis"
description: "Updates, worldbuilding, characters, and more"
baseurl: "" # Leave this blank for user.github.io repo
url: "https://caelryuujin.github.io"
theme: minima

author:
  name: "Cael"
  avatar: "assets/caelpic1.png"
  bio: "Hi there, I'm Cael. I'm the author of Umbra Solis, but in my free time I'm a physicist! Hope you'll enjoy the story and the world I'm creating!"

# Custom navigation links
header_pages:
  - index.md
  - Characterindex.md
  - Places/Places.md
  - Updates/Updates.md
  - about.md

